### ISSUE TITLE
Use MariaDB's Aria instead of MyISAM for MariaDB builds

### ISSUE THREAD

**Issue by Sarabveer** [shabados/database#1235]
https://www.percona.com/blog/2016/10/11/mysql-8-0-end-myisam/

**Comment by Harjot1Singh** [comment]
A lot of the reasons recommending Inno over MyISAM come down to when using a the DB for writes, however we don’t need any of the features Inno has (unless there’s anything that improves read performance, which, as far as I’ve read, MyISAM will lead with in read-only, don’t-care-about-locking environment).

Thoughts?

**Comment by Sarabveer** [comment]
At this point, InnoDB is on par and maybe surpasses MyISAM in reads as well. It has better concurrency as well. GurbaniNow API receives over 2M+ req/mo, I would go for better concurrency.

Other than that, MyISAM isn't really updated much anymore.

**Comment by Harjot1Singh** [comment]
https://dba.stackexchange.com/a/103814

Perhaps the answer is old, but still shows that MyISAM is much faster for read-only environments (because it isn’t ACID compliant, so doesn’t do any reads before executing a query). 

I reckon, if it’s being phased out, we could probably switch to something similar, since we really don’t care about ACID, and that would defo provide performance gains for reads if capitalised upon

**Comment by Sarabveer** [comment]
Yea, I mentioned the only thing MyISAM has over InnoDB is when using `count()`. We don't use that, not that I know of.

**Comment by Sarabveer** [comment]
Use Aria instead of MyISAM
