### ISSUE TITLE
Ang number missing in data files

### ISSUE THREAD

**Issue by SSAT** [ShabadOS/database#1761]
Hi, 
I have found there are multiple page no. (ang no.) are missing in the Sri Dasam Granth bani. Even though there data is in different file can you please explain how to grab the full source.

**Comment by bhajneet** [comment]
I believe the json files are split by section/subsection. When these go across multiples then they are saved in the starting json.

@Harjot1Singh can you explain the technicalities of pulling page/ang like done in database.shabados.com ?

**Comment by Harjot1Singh** [comment]
@SSAT if you install the npm package, or download the SQLite database, you will be able to query by page/ang. The repository is used as the "source of truth", so it is not designed to be consumed "as-is", which is why we build it into a downloadable database.

If you do look into the JSON files, you'll notice that some page files are missing, because the grouping is done by shabad, and some shabads span multiple pages. In these cases, the proceeding (missing) pages are actually included in the previous page.

Let us know if this answers your question, or if you need any more assistance!

**Comment by SSAT** [comment]
Thank you for your reply. It make sense to me now thanks.
