### ISSUE TITLE
no translation in hindi and urdu , please corcern on this what non knowing person will do if they dont knw punjabi

### ISSUE THREAD

**Issue by jasmeetsinghsc** [shabados/database#1885]
### Question

no hindi and urdu translation

**Comment by selsie** [comment]
I think the scope of this database is not to include all possible languages, but the sources given.
For Urdu and Hindi translations of Sri Guru Granth Sahib Ji there are various other sources, including https://sggsonline.com/

**Comment by bhajneet** [comment]
Thank you for explaining selsie! Going to mark this as closed.

Do you happen to know how that site produces all those translations? It seems to just be Google translated. But all the same I'm happy you shared it, I will have a closer look at some point.

**Comment by selsie** [comment]
> Thank you for explaining selsie! Going to mark this as closed.
> 
> Do you happen to know how that site produces all those translations? It seems to just be Google translated. But all the same I'm happy you shared it, I will have a closer look at some point.

I don't know how the translations are done, but all translations going 3 way, that means: "Gurbani -> English -> Whatever" will be even worse than the english translation, which is most of the time barely acceptable. I would recommend transliteration for the Punjabi translation, because Hindi and Urdu speakers should understand most of it. A Hindi translation is available on https://www.searchgurbani.com , but I don't know it's origin.
