### ISSUE TITLE
Dasam Granth Misaligned and Missing Text, Missing Text in Freedkot Teeka

### ISSUE THREAD

**Issue by amansx** [shabados/database#1886]
### Describe the bug

Hi, First of all amazing work, super helpful and informative.
I found a few issues with the database text which seems to be different in the database and SikhiToTheMax website
1. Dasam Granth Sahib::
Last line on the website on Panna 1428 is:
ਗੁਰੂ ਸ਼ਾਹ ਗੋਬਿੰਦ ਕੀ ਰੱਖ ਕੀਜੈ ॥

Whereas in the database it is::
ਗ਼ਮੇ ਹਰ ਦੁ ਆਲਮ ਫ਼ਰਾਮੋਸ਼ ਕੁਨ ॥੨੧॥੧੨॥

2. Pannas don't align with the database
Last Line on Panna 1 on SikhiToTheMax is::
ਨਮਸਤੰ ਅਭੂਤੇ ॥

whereas in the database it is::
ਨਮਸਤੰ ਅਜਾਏ ॥੩॥

3. FareedKot Teeka has missing text all over the place::
Translation for MoolMantar ends::
ਤਾਵਤ ਕਾਲ ਪਰਯੰਤ ਵਸਤੂ ਕੀ ਸਿੱਧੀ ਨਹੀਂ ਹੋਤੀ ਹੈ। ਇਸ ਸੋ

with clearly missing text

**Comment by sarabveer** [comment]
The last page of most if not all published versions of Sri Dasam Granth is 1428 and the last line line of that page is `ਗ਼ਮੇ ਹਰ ਦੁ ਆਲਮ ਫ਼ਰਾਮੋਸ਼ ਕੁਨ ॥੨੧॥੧੨॥`.

Regarding Fareedkoti Teeka, that is a known issue.

See photos below:

<img width="576" alt="image" src="https://user-images.githubusercontent.com/4297171/209191363-87dcd2e4-f09f-4f96-b7af-430ec90d7a20.png">


<img width="1005" alt="image" src="https://user-images.githubusercontent.com/4297171/209190906-ad4478ed-927b-470f-895f-1a5f3974f841.png">

**Comment by bhajneet** [comment]
Hello! Thank you for dropping us a message. One thing I'll add is the faridkot teeka came from a database that was limited to X number of characters (I think it was 255) so once the message was too long, it just truncated it. We will be re-doing these so that the original information is all available.

On the point of the Dasam Granth, we're just trying to copy the published sources as best as possible. There is a limitation to how precise we can be with aligning lines to certain panne. For example we are not able to split a line across two panne. Hopefully this can be resolved in the future as well.

If you have any desire to explore the Shabad OS Database online, you can see it here: https://viewer.next.shabados.com/ This is an experimental project and a WIP, so there can be unexpected changes in the future.

Let us know if you have any more questions, I believe this one has been sufficiently answered, so I'm closing it. However, if you feel this is not resolved, just comment back here and we can communicate about it further!

**Comment by amansx** [comment]
Hey,
Thanks a bunch I'm working on a similar software to visualize ShabadOS Database,
It's a Mac/Windows Native OpenGL app that supports elastic search and utilizes SantLipi font

<img width="1792" alt="Screen Shot 2022-12-23 at 12 00 19 AM" src="https://user-images.githubusercontent.com/5609315/209274120-37ea2ca6-8033-4fa1-b3db-029263cae3b7.png">

Let me know if I can help with parsing of Granth Sahibans and other texts right now if you could provide raw text for
1. FareedKot Teeka
2. Mahan Kosh

I can modify SantLipi to support additional Mahan Kosh Characters

**Comment by amansx** [comment]
Also IDs such as 0NVY do they have a numerical representation? Why not simply use integers followed by a granth ID

**Comment by bhajneet** [comment]
Thank you for your interest! I will let @Harjot1Singh answer these questions. He is the lead developer of our organization.

**Comment by amansx** [comment]
@Harjot1Singh suggestions?
